import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { expect, test } from 'vitest'
import { resolveWindow, type SessionQuery } from '@l5ng/yaohe-core'
import { collectClaude } from './claude.js'
import { sessionCollectorListener, stripControlWrappers, unwrapUserQuery } from './sessions.js'

function json(record: Record<string, unknown>): string {
  return `${JSON.stringify(record)}\n`
}

test('unwrapUserQuery only unwraps a whole non-empty user_query', () => {
  expect(unwrapUserQuery('<user_query>build login</user_query>')).toBe('build login')
  expect(unwrapUserQuery('<user_query>\nbuild login\n</user_query>')).toBe('build login')
  expect(unwrapUserQuery('<user_query></user_query>')).toBe('<user_query></user_query>')
  expect(unwrapUserQuery('<user_query>x</user_query> trailing')).toBe(
    '<user_query>x</user_query> trailing',
  )
  expect(unwrapUserQuery('plain text')).toBe('plain text')
})

test('stripControlWrappers removes leading wrappers and keeps real text', () => {
  expect(stripControlWrappers('<system-reminder>continue</system-reminder>\n\nfix the tests')).toBe(
    'fix the tests',
  )
  expect(
    stripControlWrappers(
      '<command-message><command-name>bash</command-name>run setup</command-message>\n\nmigrate',
    ),
  ).toBe('migrate')
  expect(
    stripControlWrappers(
      '<local-command-stdout>\noutput\n</local-command-stdout>\n\ncaveat: run locally',
    ),
  ).toBe('caveat: run locally')
  const unbalanced = '<system-reminder>unclosed\nfix the tests'
  expect(stripControlWrappers(unbalanced)).toBe(unbalanced)
  expect(stripControlWrappers('plain text')).toBe('plain text')
})

test('keeps real text after wrappers and unwraps user_query', async () => {
  const temp = mkdtempSync(join(tmpdir(), 'yaohe-claude-'))
  const project = join(temp, 'project')
  const sessions = join(temp, 'sessions')
  mkdirSync(project)
  mkdirSync(join(sessions, 'projects'), { recursive: true })
  const path = join(sessions, 'projects', 's2.jsonl')

  const content = [
    json({
      type: 'user',
      sessionId: 's2',
      cwd: project,
      timestamp: '2026-07-22T01:00:00Z',
      message: { role: 'user', content: '<system-reminder>Please continue</system-reminder>\n\nfix the tests' },
    }),
    json({
      type: 'user',
      cwd: project,
      timestamp: '2026-07-22T01:01:00Z',
      message: { role: 'user', content: '<user_query>implement login</user_query>' },
    }),
    json({
      type: 'user',
      cwd: project,
      timestamp: '2026-07-22T01:02:00Z',
      message: {
        role: 'user',
        content: '<command-message><command-name>bash</command-name>run setup</command-message>\n\nmigrate the schema',
      },
    }),
    json({
      type: 'user',
      cwd: project,
      timestamp: '2026-07-22T01:03:00Z',
      message: {
        role: 'user',
        content:
          '<local-command-stdout>\noutput\n</local-command-stdout>\n\ncaveat: the messages below were generated by the user while running local commands',
      },
    }),
  ].join('')
  writeFileSync(path, content)

  const query: SessionQuery = {
    gitRoots: [project],
    window: resolveWindow('2026-07-22', 'UTC'),
  }
  try {
    process.env.CLAUDE_CONFIG_DIR = sessions
    const slice = await collectClaude(query)
    const texts = slice.prompts.map((prompt) => prompt.text)
    expect(texts).toContain('fix the tests')
    expect(texts).toContain('implement login')
    expect(texts).toContain('migrate the schema')
    expect(texts).not.toContain('Please continue')
    expect(texts).not.toContain('caveat:')
    expect(texts).not.toContain('<user_query>')
    expect(slice.prompts.length).toBe(3)
  } finally {
    delete process.env.CLAUDE_CONFIG_DIR
  }
})

test('keeps only human text and skips injections', async () => {
  const temp = mkdtempSync(join(tmpdir(), 'yaohe-claude-'))
  const project = join(temp, 'project')
  const sessions = join(temp, 'sessions')
  mkdirSync(project)
  mkdirSync(join(sessions, 'projects'), { recursive: true })
  const path = join(sessions, 'projects', 's1.jsonl')

  const content = [
    json({ type: 'user', sessionId: 's1', cwd: project, timestamp: '2026-07-22T01:00:00Z', message: { role: 'user', content: 'implement login' } }),
    json({ type: 'user', cwd: project, timestamp: '2026-07-22T01:01:00Z', message: { role: 'user', content: [{ type: 'tool_result', content: 'secret' }, { type: 'text', text: 'fix the tests' }] } }),
    json({ type: 'user', cwd: project, timestamp: '2026-07-22T01:02:00Z', isMeta: true, message: { role: 'user', content: 'meta' } }),
    json({ type: 'user', cwd: project, timestamp: '2026-07-22T01:03:00Z', message: { role: 'user', content: '/compact' } }),
    'not-json\n',
  ].join('')
  writeFileSync(path, content)

  const query: SessionQuery = {
    gitRoots: [project],
    window: resolveWindow('2026-07-22', 'UTC'),
  }
  try {
    process.env.CLAUDE_CONFIG_DIR = sessions
    const slice = await collectClaude(query)
    expect(slice.prompts.length).toBe(2)
    expect(slice.prompts[0].text).toBe('implement login')
    expect(slice.prompts[1].text).toBe('fix the tests')
    expect(slice.prompts[1].text).not.toContain('secret')
  } finally {
    delete process.env.CLAUDE_CONFIG_DIR
  }
})

test('filters sessions outside the git roots', async () => {
  const temp = mkdtempSync(join(tmpdir(), 'yaohe-claude-'))
  const project = join(temp, 'project')
  const other = join(temp, 'other')
  const sessions = join(temp, 'sessions')
  mkdirSync(project)
  mkdirSync(other)
  mkdirSync(join(sessions, 'projects'), { recursive: true })
  writeFileSync(
    join(sessions, 'projects', 'elsewhere.jsonl'),
    `${JSON.stringify({ type: 'user', sessionId: 'e', cwd: other, timestamp: '2026-07-22T01:00:00Z', message: { role: 'user', content: 'another project' } })}\n`,
  )
  const query: SessionQuery = {
    gitRoots: [project],
    window: resolveWindow('2026-07-22', 'UTC'),
  }
  try {
    process.env.CLAUDE_CONFIG_DIR = sessions
    const slice = await collectClaude(query)
    expect(slice.prompts.length).toBe(0)
  } finally {
    delete process.env.CLAUDE_CONFIG_DIR
  }
})

test('session collector listener isolates failures into warnings', async () => {
  const listener = sessionCollectorListener('broken', async () => {
    throw new Error('boom')
  })
  const acc = { prompts: [], warnings: [] }
  await listener({ gitRoots: ['/tmp'], window: resolveWindow('2026-07-22', 'UTC') }, acc)
  expect(acc.prompts.length).toBe(0)
  expect(acc.warnings[0]).toContain('broken')
  expect(acc.warnings[0]).toContain('boom')
})
