import { readFile } from 'node:fs/promises'
import { homedir } from 'node:os'
import { basename, join } from 'node:path'
import type { Context } from 'cordis'
import {
  parseTimestamp,
  windowContains,
  type SessionEvidence,
  type SessionQuery,
  type UserPrompt,
} from '@l5ng/yaohe-core'
import {
  extractTextItems,
  pathIsWithin,
  readJsonlLines,
  sessionCollectorListener,
  walkJsonl,
} from './sessions.js'

export const name = 'collector-claude-sessions'

export const claudePlugin = { name, apply }

export function apply(ctx: Context): void {
  ctx.on('evidence/session', sessionCollectorListener('claude', collectClaude))
}

export async function collectClaude(query: SessionQuery): Promise<SessionEvidence> {
  const root = claudeProjectsRoot()
  if (!root) return { prompts: [], warnings: [] }
  let files: string[]
  try {
    files = await walkJsonl(root)
  } catch {
    return { prompts: [], warnings: [] }
  }
  const prompts: UserPrompt[] = []
  for (const file of files) {
    if (basename(file).startsWith('agent-')) continue
    const filePrompts = await parseClaudeFile(file, query)
    prompts.push(...filePrompts)
  }
  return { prompts, warnings: [] }
}

function claudeProjectsRoot(): string | null {
  const env = process.env.CLAUDE_CONFIG_DIR
  return env ? join(env, 'projects') : join(homedir(), '.claude', 'projects')
}

export async function parseClaudeFile(
  path: string,
  query: SessionQuery,
): Promise<UserPrompt[]> {
  const fileText = await readFile(path, 'utf8')
  const fallbackSessionId = basename(path).replace(/\.jsonl$/, '') || 'unknown'
  let sessionId: string | null = null
  let sessionCwd: string | null = null
  const candidates: Array<{ timestamp: string; text: string; recordId: string; cwd: string | null }> = []

  readJsonlLines(fileText, (value, lineIndex) => {
    if (sessionId === null) {
      const valueId = value.sessionId
      if (typeof valueId === 'string') sessionId = valueId
    }
    if (sessionCwd === null) {
      const valueCwd = value.cwd
      if (typeof valueCwd === 'string') sessionCwd = valueCwd
    }
    if (value.type !== 'user' || value.isMeta === true || value.isSidechain === true) return
    const message = value.message
    if (typeof message !== 'object' || message === null) return
    const record = message as Record<string, unknown>
    if (record.role !== 'user') return
    const text = extractTextItems(record.content, ['text'])
    if (shouldSkipText(text)) return
    const instant = parseTimestamp(value.timestamp)
    if (!instant || !windowContains(query.window, instant)) return
    const recordId = value.uuid ?? value.id
    const cwd = value.cwd
    candidates.push({
      timestamp: instant.toJSON(),
      text,
      recordId: typeof recordId === 'string' ? recordId : String(lineIndex),
      cwd: typeof cwd === 'string' ? cwd : null,
    })
  })

  const cwd = sessionCwd ?? candidates.find((candidate) => candidate.cwd !== null)?.cwd ?? null
  if (!cwd || !query.gitRoots.some((root) => pathIsWithin(cwd, root))) return []

  const sessionIdValue = sessionId ?? fallbackSessionId
  const seen = new Set<string>()
  const prompts: UserPrompt[] = []
  for (const candidate of candidates) {
    const key = `claude\0${sessionIdValue}\0${candidate.timestamp}\0${candidate.recordId}`
    if (seen.has(key)) continue
    seen.add(key)
    prompts.push({
      provider: 'claude',
      session_id: sessionIdValue,
      timestamp: candidate.timestamp,
      cwd,
      text: candidate.text,
      record_id: candidate.recordId,
    })
  }
  return prompts
}

export function shouldSkipText(text: string): boolean {
  const trimmed = text.trim()
  if (trimmed === '' || trimmed.startsWith('/')) return true
  const lower = trimmed.toLowerCase()
  return [
    '<local-command-caveat>',
    '<local-command-stdout>',
    '<command-name>',
    '<system-reminder>',
    'caveat: the messages below were generated by the user while running local commands',
  ].some((prefix) => lower.startsWith(prefix))
}
